### ISSUE TITLE
Style adjustment: Bullet color

### ISSUE THREAD

**Issue by admoorgit** [coram-uk/coram-playbook#13]
Issue: Bullet color is very light, which makes them hard to see
<img width="109" alt="image" src="https://github.com/coram-uk/coram-playbook/assets/72033897/6000c8dd-18be-48af-962f-31aaf14d2fec">

Suggested fix: Change bullet color to black.

**Comment by jeffmaher-bloom** [comment]
Fix coming

**Comment by jeffmaher-bloom** [comment]
Fixed:

![image](https://github.com/coram-uk/coram-playbook/assets/149111526/e5c97777-f3ad-47e8-8acd-c0dbfa39d8af)
