### ISSUE TITLE
Request: Can we make the search field active when the search page loads?

### ISSUE THREAD

**Issue by admoorgit** [coram-uk/coram-playbook#16]
Suggestion: Would be nice if, when someone clicks "Search", they land on the page and the field is active so they can start typing, or, on mobile, the keyboard pops up immediately. Is a nicer experience than having to click search in nav, then the field on the page.

**Comment by jeffmaher-bloom** [comment]
Won't fix since this would be an anti-pattern for folks using a screen reader.
