### ISSUE TITLE
NAVIGATION / HEADER ISSUE — Mobile header expanded by default and can't be collapsed

### ISSUE THREAD

**Issue by admoorgit** [coram-uk/coram-playbook#2]
**Issue:** When the viewport is at mobile width, the mobile menu button appears but is nonfunctional. Menu items cannot be collapsed or expanded.

**Expected functionality:** 
- Mobile menu is collapsed by default and is accessed via menu button press
- Navigation items underlined on hover (in case someone is using a very thin browser window)
- Menu icon changes to "X" when open 

[Video](https://watch.screencastify.com/v/mXXN14Mchj0GH2s6D2sr)

**Comment by jeffmaher-bloom** [comment]
Done
