### ISSUE TITLE
Are the headings/titles on the sub pages fixed or is there any way we can amend this?

### ISSUE THREAD

**Issue by SylvieTravers** [coram-uk/coram-playbook#24]
**Describe the bug**
We wondered whether we can amend headings/titles on each page or if they are fixed. For example, on the topics page, would we be able to tweak 'What we can do?' to 'What are organisations are doing to address this?' ourselves or is it fixed? From playing around on the CMS, it looks like that part is fixed.

**Screenshots**

<img width="320" alt="About this topic" src="https://github.com/coram-uk/coram-playbook/assets/148966302/85b3aa8f-f638-4a21-acd2-11c14a7b61cf">

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]: Microsoft Edge
 - Version [e.g. 22] 114.0.1823.86

**Additional context**

**Comment by bloom-hondo** [comment]
These are editable now
