### ISSUE TITLE
Cannot see some topics on the CMS to add/take off the home page

### ISSUE THREAD

**Issue by SylvieTravers** [coram-uk/coram-playbook#27]
**Describe the bug**
We have tried to add a couple of topics e.g. Early Help and Intervention. It appears on the main site in the topics list but on the CMS under the Topics on Main Page, it doesn't appear to select. Conversely, some of the topics not selected on the CMS appear on the home page e.g. Finding Kin

**To Reproduce**
1. Go to 'Pages' on the CMS
2. Click on 'Main page'
3. Scroll down to 'Topics'
4. Not all topics appear to select

**Expected behavior**
To be able to select and de-select topics on the CMS which correlates to the topics appearing on the main site.

**Screenshots**

I can't seem to screenshot with the list open on the CMS- sorry!

<img width="386" alt="image" src="https://github.com/coram-uk/coram-playbook/assets/148966302/f3a1bca6-d2aa-4b5b-b39b-53f67b0ffdd4">

<img width="874" alt="topics issue 2" src="https://github.com/coram-uk/coram-playbook/assets/148966302/6625e35b-a56d-43fc-9ff9-6f06f28b069c">

**Desktop (please complete the following information):**
Browser [e.g. chrome, safari]: Microsoft Edge
Version [e.g. 22] 114.0.1823.86

**Additional context**

**Comment by bloom-hondo** [comment]
@SylvieTravers this should be fixed. I updated the CMS so that it shows the proper title of things as well.

**Comment by SylvieTravers** [comment]
Perfect, thanks. That's all working :)
