### ISSUE TITLE
Searching on Projects page

### ISSUE THREAD

**Issue by SylvieTravers** [coram-uk/coram-playbook#28]
**Describe the bug**
When you search on the project page, the projects come up but all the other letters are visible as blanks.

**To Reproduce**
1. Go to 'Projects page'
2. Search e.g. 'Be gentle when interacting with kin for the first time'
3. Project appears but all other letters are visible too

**Expected behavior**
For just that topic to appear without all the other blanks appearing.

**Screenshots**

<img width="950" alt="projects search" src="https://github.com/coram-uk/coram-playbook/assets/148966302/c5d061cf-4ff6-4dc4-a14f-9f7a4bceab6a">

**Desktop (please complete the following information):**
 Browser [e.g. chrome, safari]: Microsoft Edge
Version [e.g. 22] 114.0.1823.86

**Additional context**

**Comment by SylvieTravers** [comment]
Sorry to be a pain but I think this might still be happening in some cases- if you were able to fix that would be great, although don't worry if not! Thanks :)

<img width="863" alt="projects search 2" src="https://github.com/coram-uk/coram-playbook/assets/148966302/67e9c0d9-e145-43c3-af17-c10f85c0ba5a">

**Comment by jeffmaher-bloom** [comment]
@bloom-hondo : In the example that @SylvieTravers shared above, `designate` doesn't show up in the title or the project page for the non-letter-`D` results. Can you look into why that might be happening?

**Comment by bloom-hondo** [comment]
Have updated this. It was searching everything within the project.
