### ISSUE TITLE
'Click here to see more topics' button on home page links to home page not the topic page.

### ISSUE THREAD

**Issue by SylvieTravers** [coram-uk/coram-playbook#32]
**Describe the bug**
I have changed the button under topics on the home page to say 'Click here to see more topics'. If you click on that from the main site, it goes to the main page rather than the topics page.

**To Reproduce**
1. Go to 'main page'
2. Scroll down to 'Topics'
3. Click on 'Click here to see more topics'

**Expected behavior**
To be taken to the topics page when you click on 'click here to see more topics'.

**Comment by jeffmaher-bloom** [comment]
Took a look into the CMS, and saw this link for the button which would just send to the same page:

![image](https://github.com/coram-uk/coram-playbook/assets/149111526/861fe0e2-c915-4dc7-afc4-64ddf4375d32)

I've updated it from `#` to `/topics`:

![image](https://github.com/coram-uk/coram-playbook/assets/149111526/c180a4e7-3e52-469f-9fc3-ee64fd01ffa9)

However, the URL doesn't seem to stick. I downloaded the built files from Netlify, and saw this in the `index.html` file.

![image](https://github.com/coram-uk/coram-playbook/assets/149111526/838fdf36-5604-497a-8f70-2f5e0aacc427)


@bloom-hondo : If you can take a look, that'd be great. In the meantime, I'll snag a local build to verify this is happening locally too.

**Comment by jeffmaher-bloom** [comment]
Confirming that updating it in the CMS doesn't change the link. From a fresh local build.

Data blurb:
![image](https://github.com/coram-uk/coram-playbook/assets/149111526/a1e2c370-5011-4242-967b-7e4afe4e861a)


Rendered site:
![image](https://github.com/coram-uk/coram-playbook/assets/149111526/1fac5bde-afba-49a7-98e4-c3cb24e03a46)

**Comment by bloom-hondo** [comment]
Updated the object to the right name.
