### ISSUE TITLE
Style adjustment: Footer social button hover states

### ISSUE THREAD

**Issue by admoorgit** [coram-uk/coram-playbook#4]
Issue: Social media icons in footer need visual feedback on hover

Proposed style fix: Change icon from black to red on hover
<img width="357" alt="image" src="https://github.com/coram-uk/coram-playbook/assets/72033897/776f8a21-179d-4f81-8d0a-f2f63c605eda">

**Comment by jeffmaher-bloom** [comment]
Fix coming
